# -*- encoding: utf-8 -*-

from tuve.util.mock import NamespaceMock, ClassNamePrintMeta, freeze_mock

TokyoMetro = NamespaceMock('TokyoMetro') # for meta variable

# Stations
TokyoMetro.Ginza.AoyamaItchome              # 青山一丁目
TokyoMetro.Hanzomon.AoyamaItchome           # 青山一丁目
TokyoMetro.Chiyoda.Akasaka                  # 赤坂
TokyoMetro.Chiyoda.Ayase                    # 綾瀬
TokyoMetro.Ginza.AkasakaMitsuke             # 赤坂見附
TokyoMetro.Marunouchi.AkasakaMitsuke        # 赤坂見附
TokyoMetro.Namboku.AkabaneIwabuchi          # 赤羽岩淵
TokyoMetro.Hibiya.Akihabara                 # 秋葉原
TokyoMetro.Ginza.Asakusa                    # 浅草
TokyoMetro.Namboku.AzabuJuban               # 麻布十番
TokyoMetro.Marunouchi.Awajicho              # 淡路町
TokyoMetro.Tozai.Iidabashi                  # 飯田橋
TokyoMetro.Yurakucho.Iidabashi              # 飯田橋
TokyoMetro.Namboku.Iidabashi                # 飯田橋
TokyoMetro.Marunouchi.Ikebukuro             # 池袋
TokyoMetro.Yurakucho.Ichigaya               # 市ケ谷
TokyoMetro.Ginza.Inaricho                   # 稲荷町
TokyoMetro.Yurakucho.Ikebukuro              # 池袋
TokyoMetro.Fukutoshin.Ikebukuro             # 池袋
TokyoMetro.Namboku.Ichigaya                 # 市ケ谷
TokyoMetro.Hibiya.Iriya                     # 入谷
TokyoMetro.Ginza.Ueno                       # 上野
TokyoMetro.Hibiya.Ueno                      # 上野
TokyoMetro.Ginza.UenoHirokoji               # 上野広小路
TokyoMetro.Tozai.Urayasu                    # 浦安
TokyoMetro.Yurakucho.Edogawabashi           # 江戸川橋
TokyoMetro.Hibiya.Ebisu                     # 恵比寿
TokyoMetro.Namboku.Oji                      # 王子
TokyoMetro.Namboku.OjiKamiya                # 王子神谷
TokyoMetro.Marunouchi.Otemachi              # 大手町
TokyoMetro.Tozai.Otemachi                   # 大手町
TokyoMetro.Chiyoda.Otemachi                 # 大手町
TokyoMetro.Hanzomon.Otemachi                # 大手町
TokyoMetro.Marunouchi.Ogikubo               # 荻窪
TokyoMetro.Hanzomon.Oshiage                 # 押上〈スカイツリー前〉
TokyoMetro.Tozai.Ochiai                     # 落合
TokyoMetro.Marunouchi.Ochanomizu            # 御茶ノ水
TokyoMetro.Ginza.OmoteSando                 # 表参道
TokyoMetro.Chiyoda.OmoteSando               # 表参道
TokyoMetro.Hanzomon.OmoteSando              # 表参道
TokyoMetro.Ginza.Gaiemmae                   # 外苑前
TokyoMetro.Tozai.Kagurazaka                 # 神楽坂
TokyoMetro.Tozai.Kasai                      # 葛西
TokyoMetro.Marunouchi.Kasumigaseki          # 霞ケ関
TokyoMetro.Hibiya.Kasumigaseki              # 霞ケ関
TokyoMetro.Chiyoda.Kasumigaseki             # 霞ケ関
TokyoMetro.Yurakucho.Kanamecho              # 要町
TokyoMetro.Fukutoshin.Kanamecho             # 要町
TokyoMetro.Hibiya.Kamiyacho                 # 神谷町
TokyoMetro.Hibiya.Kayabacho                 # 茅場町
TokyoMetro.Tozai.Kayabacho                  # 茅場町
TokyoMetro.Ginza.Kanda                      # 神田
TokyoMetro.Chiyoda.KitaAyase                # 北綾瀬
TokyoMetro.Fukutoshin.KitaSando             # 北参道
TokyoMetro.Hibiya.KitaSenju                 # 北千住
TokyoMetro.Chiyoda.KitaSenju                # 北千住
TokyoMetro.Tozai.Kiba                       # 木場
TokyoMetro.Tozai.Gyotoku                    # 行徳
TokyoMetro.Ginza.Kyobashi                   # 京橋
TokyoMetro.Hanzomon.KiyosumiShirakawa       # 清澄白河
TokyoMetro.Ginza.Ginza                      # 銀座
TokyoMetro.Marunouchi.Ginza                 # 銀座
TokyoMetro.Hibiya.Ginza                     # 銀座
TokyoMetro.Yurakucho.GinzaItchome           # 銀座一丁目
TokyoMetro.Hanzomon.Kinshicho               # 錦糸町
TokyoMetro.Tozai.Kudanshita                 # 九段下
TokyoMetro.Hanzomon.Kudanshita              # 九段下
TokyoMetro.Yurakucho.Kojimachi              # 麴町
TokyoMetro.Marunouchi.Korakuen              # 後楽園
TokyoMetro.Namboku.Korakuen                 # 後楽園
TokyoMetro.Yurakucho.Gokokuji               # 護国寺
TokyoMetro.Yurakucho.KotakeMukaihara        # 小竹向原
TokyoMetro.Fukutoshin.KotakeMukaihara       # 小竹向原
TokyoMetro.Marunouchi.KokkaiGijidomae       # 国会議事堂前
TokyoMetro.Chiyoda.KokkaiGijidomae          # 国会議事堂前
TokyoMetro.Hibiya.Kodemmacho                # 小伝馬町
TokyoMetro.Namboku.Komagome                 # 駒込
TokyoMetro.Yurakucho.Sakuradamon            # 桜田門
TokyoMetro.Ginza.Shibuya                    # 渋谷
TokyoMetro.Hanzomon.Shibuya                 # 渋谷
TokyoMetro.Fukutoshin.Shibuya               # 渋谷
TokyoMetro.Namboku.Shimo                    # 志茂
TokyoMetro.Namboku.Shirokanedai             # 白金台
TokyoMetro.Namboku.ShirokaneTakanawa        # 白金高輪
TokyoMetro.Marunouchi.ShinOtsuka            # 新大塚
TokyoMetro.Chiyoda.ShinOchanomizu           # 新御茶ノ水
TokyoMetro.Yurakucho.ShinKiba               # 新木場
TokyoMetro.Marunouchi.ShinKoenji            # 新高円寺
TokyoMetro.Marunouchi.Shinjuku              # 新宿
TokyoMetro.Marunouchi.ShinjukuGyoemmae      # 新宿御苑前
TokyoMetro.Marunouchi.ShinjukuSanchome      # 新宿三丁目
TokyoMetro.Fukutoshin.ShinjukuSanchome      # 新宿三丁目
TokyoMetro.Yurakucho.Shintomicho            # 新富町
TokyoMetro.Marunouchi.ShinNakano            # 新中野
TokyoMetro.Ginza.Shimbashi                  # 新橋
TokyoMetro.Hanzomon.Jimbocho                # 神保町
TokyoMetro.Hanzomon.Suitengumae             # 水天宮前
TokyoMetro.Ginza.Suehirocho                 # 末広町
TokyoMetro.Hanzomon.Sumiyoshi               # 住吉
TokyoMetro.Yurakucho.Senkawa                # 千川
TokyoMetro.Fukutoshin.Senkawa               # 千川
TokyoMetro.Chiyoda.Sendagi                  # 千駄木
TokyoMetro.Fukutoshin.Zoshigaya             # 雑司が谷
TokyoMetro.Tozai.Takadanobaba               # 高田馬場
TokyoMetro.Tozai.Takebashi                  # 竹橋
TokyoMetro.Yurakucho.Tatsumi                # 辰巳
TokyoMetro.Ginza.TameikeSanno               # 溜池山王
TokyoMetro.Namboku.TameikeSanno             # 溜池山王
TokyoMetro.Ginza.Tawaramachi                # 田原町
TokyoMetro.Yurakucho.ChikatetsuAkatsuka     # 地下鉄赤塚
TokyoMetro.Yurakucho.ChikatetsuNarimasu     # 地下鉄成増
TokyoMetro.Hibiya.Tsukiji                   # 築地
TokyoMetro.Yurakucho.Tsukishima             # 月島
TokyoMetro.Marunouchi.Tokyo                 # 東京
TokyoMetro.Namboku.Todaimae                 # 東大前
TokyoMetro.Tozai.Toyocho                    # 東陽町
TokyoMetro.Yurakucho.Toyosu                 # 豊洲
TokyoMetro.Ginza.Toranomon                  # 虎ノ門
TokyoMetro.Hibiya.NakaOkachimachi           # 仲御徒町
TokyoMetro.Yurakucho.Nagatacho              # 永田町
TokyoMetro.Hanzomon.Nagatacho               # 永田町
TokyoMetro.Namboku.Nagatacho                # 永田町
TokyoMetro.Tozai.Nakano                     # 中野
TokyoMetro.Marunouchi.NakanoSakaue          # 中野坂上
TokyoMetro.MarunouchiBranch.NakanoShimbashi # 中野新橋
TokyoMetro.MarunouchiBranch.NakanoFujimicho # 中野富士見町
TokyoMetro.Hibiya.NakaMeguro                # 中目黒
TokyoMetro.Tozai.NishiKasai                 # 西葛西
TokyoMetro.Namboku.Nishigahara              # 西ケ原
TokyoMetro.Marunouchi.NishiShinjuku         # 西新宿
TokyoMetro.Chiyoda.NishiNippori             # 西日暮里
TokyoMetro.Tozai.NishiFunabashi             # 西船橋
TokyoMetro.Fukutoshin.NishiWaseda           # 西早稲田
TokyoMetro.Chiyoda.Nijubashimae             # 二重橋前
TokyoMetro.Ginza.Nihombashi                 # 日本橋
TokyoMetro.Tozai.Nihombashi                 # 日本橋
TokyoMetro.Hibiya.Ningyocho                 # 人形町
TokyoMetro.Chiyoda.Nezu                     # 根津
TokyoMetro.Chiyoda.Nogizaka                 # 乃木坂
TokyoMetro.Hibiya.Hatchobori                # 八丁堀
TokyoMetro.Tozai.BarakiNakayama             # 原木中山
TokyoMetro.Hanzomon.Hanzomon                # 半蔵門
TokyoMetro.Yurakucho.HigashiIkebukuro       # 東池袋
TokyoMetro.Hibiya.HigashiGinza              # 東銀座
TokyoMetro.Marunouchi.HigashiKoenji         # 東高円寺
TokyoMetro.Fukutoshin.HigashiShinjuku       # 東新宿
TokyoMetro.Yurakucho.Hikawadai              # 氷川台
TokyoMetro.Hibiya.Hibiya                    # 日比谷
TokyoMetro.Chiyoda.Hibiya                   # 日比谷
TokyoMetro.Hibiya.HiroO                     # 広尾
TokyoMetro.Yurakucho.Heiwadai               # 平和台
TokyoMetro.MarunouchiBranch.Honancho        # 方南町
TokyoMetro.Marunouchi.HongoSanchome         # 本郷三丁目
TokyoMetro.Namboku.HonKomagome              # 本駒込
TokyoMetro.Chiyoda.Machiya                  # 町屋
TokyoMetro.Ginza.Mitsukoshimae              # 三越前
TokyoMetro.Hanzomon.Mitsukoshimae           # 三越前
TokyoMetro.Marunouchi.MinamiAsagaya         # 南阿佐ケ谷
TokyoMetro.Tozai.MinamiGyotoku              # 南行徳
TokyoMetro.Tozai.MinamiSunamachi            # 南砂町
TokyoMetro.Hibiya.MinamiSenju               # 南千住
TokyoMetro.Hibiya.Minowa                    # 三ノ輪
TokyoMetro.Marunouchi.Myogadani             # 茗荷谷
TokyoMetro.Tozai.Myoden                     # 妙典
TokyoMetro.Chiyoda.MeijiJingumae            # 明治神宮前〈原宿〉
TokyoMetro.Fukutoshin.MeijiJingumae         # 明治神宮前〈原宿〉
TokyoMetro.Namboku.Meguro                   # 目黒
TokyoMetro.Tozai.MonzenNakacho              # 門前仲町
TokyoMetro.Yurakucho.Yurakucho              # 有楽町
TokyoMetro.Chiyoda.Yushima                  # 湯島
TokyoMetro.Marunouchi.Yotsuya               # 四ツ谷
TokyoMetro.Namboku.Yotsuya                  # 四ツ谷
TokyoMetro.Marunouchi.YotsuyaSanchome       # 四谷三丁目
TokyoMetro.Chiyoda.YoyogiUehara             # 代々木上原
TokyoMetro.Chiyoda.YoyogiKoen               # 代々木公園
TokyoMetro.Hibiya.Roppongi                  # 六本木
TokyoMetro.Namboku.RoppongiItchome          # 六本木一丁目
TokyoMetro.Yurakucho.Wakoshi                # 和光市
TokyoMetro.Tozai.Waseda                     # 早稲田
TokyoMetro.MarunouchiBranch.NakanoSakaue    # 中野坂上
TokyoMetro.Fukutoshin.Hikawadai             # 氷川台
TokyoMetro.Fukutoshin.Heiwadai              # 平和台
TokyoMetro.Fukutoshin.ChikatetsuAkatsuka    # 地下鉄赤塚
TokyoMetro.Fukutoshin.ChikatetsuNarimasu    # 地下鉄成増
TokyoMetro.Fukutoshin.Wakoshi               # 和光市

# Train Type
TokyoMetro.Unknown                # 不明
TokyoMetro.Local                  # 各停
TokyoMetro.Express                # 急行
TokyoMetro.Rapid                  # 快速
TokyoMetro.SemiExpress            # 準急
TokyoMetro.TamaExpress            # 多摩急行
TokyoMetro.HolidayExpress         # 土休急行
TokyoMetro.CommuterSemiExpress    # 通勤準急
TokyoMetro.Extra                  # 臨時
TokyoMetro.RomanceCar             # 特急ロマンスカー
TokyoMetro.RapidExpress           # 快速急行
TokyoMetro.CommuterExpress        # 通勤急行
TokyoMetro.LimitedExpress         # 特急
TokyoMetro.CommuterLimitedExpress # 通勤特急
TokyoMetro.CommuterRapid          # 通勤快速
TokyoMetro.ToyoRapid              # 東葉快速

# Railway
TokyoMetro.Ginza      # 東京メトロ銀座線
TokyoMetro.Marunouchi # 東京メトロ丸ノ内線
TokyoMetro.Hibiya     # 東京メトロ日比谷線
TokyoMetro.Tozai      # 東京メトロ東西線
TokyoMetro.Chiyoda    # 東京メトロ千代田線
TokyoMetro.Yurakucho  # 東京メトロ有楽町線
TokyoMetro.Hanzomon   # 東京メトロ半蔵門線
TokyoMetro.Namboku    # 東京メトロ南北線
TokyoMetro.Fukutoshin # 東京メトロ副都心線

# Rail Direction
TokyoMetro.Asakusa           # 浅草方面
TokyoMetro.Ogikubo           # 荻窪方面
TokyoMetro.Ikebukuro         # 池袋方面
TokyoMetro.Honancho          # 方南町方面
TokyoMetro.NakanoSakaue      # 中野坂上方面
TokyoMetro.NakaMeguro        # 中目黒方面
TokyoMetro.KitaSenju         # 北千住方面
TokyoMetro.NishiFunabashi    # 西船橋方面
TokyoMetro.Nakano            # 中野方面
TokyoMetro.YoyogiUehara      # 代々木上原方面
TokyoMetro.Ayase             # 綾瀬方面
TokyoMetro.KitaAyase         # 北綾瀬方面
TokyoMetro.ShinKiba          # 新木場方面
TokyoMetro.Ikebukuro         # 池袋方面
TokyoMetro.Oshiage           # 押上方面
TokyoMetro.Shibuya           # 渋谷方面
TokyoMetro.AkabaneIwabuchi   # 赤羽岩淵方面
TokyoMetro.Meguro            # 目黒方面
TokyoMetro.ShirokaneTakanawa # 白金高輪方面
TokyoMetro.Wakoshi           # 和光市方面
TokyoMetro.KotakeMukaihara   # 小竹向原方面

TokyoMetro = freeze_mock(TokyoMetro, metaclass=ClassNamePrintMeta)
